import 'package:flutter/material.dart';

class AppTheme {
  ThemeData get themeData => ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          primary: Color(0XFFa076f2),
          onBackground: Color(0XFF555555),
          background: Color(0XFFf7f7f7),
          surface: Color(0XFFFFFFFF),
          onSurface: Color(0XFF9e9e9e),
          onPrimary: Color(0XFFFFFFFF),
          secondary: Color(0XFFFFFFFF),
          onSecondary: Color(0XFFFFFFFF),
          error: Color(0XFFFFFFFF),
          onError: Color(0XFFFFFFFF),
          brightness: Brightness.light,
        ),
      );

  TextTheme get textTheme => const TextTheme(
        displayLarge: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 24.0,
          letterSpacing: 0.12,
          height: 1.5,
        ),
        displayMedium: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 22.0,
          letterSpacing: 0.12,
          height: 1.5,
        ),
        displaySmall: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 20.0,
          letterSpacing: 0.12,
          height: 1.5,
        ),
        headlineMedium: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 18.0,
          letterSpacing: 0.12,
          height: 1.5,
        ),
        headlineSmall: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 16.0,
          letterSpacing: 0.12,
          height: 1.5,
        ),
        titleLarge: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 14.0,
          letterSpacing: 0.12,
          height: 1.5,
        ),
        titleMedium: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.w600,
          fontStyle: FontStyle.normal,
          fontSize: 20.0,
          letterSpacing: 0.09,
          height: 1.5,
        ),
        titleSmall: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.w600,
          fontStyle: FontStyle.normal,
          fontSize: 18.0,
          letterSpacing: 0.09,
          height: 1.5,
        ),
        bodyLarge: TextStyle(
          fontFamily: "Heebo",
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          fontSize: 18.0,
          letterSpacing: 0.0,
          height: 1.5,
        ),
        bodyMedium: TextStyle(
          fontFamily: "Heebo",
          fontSize: 16.0,
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          letterSpacing: 0.0,
          height: 1.5,
        ),
        bodySmall: TextStyle(
          fontFamily: "Heebo",
          fontSize: 14.0,
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          letterSpacing: 0.0,
          height: 1.5,
        ),
        labelLarge: TextStyle(
          fontFamily: "Heebo",
          fontSize: 16.0,
          fontWeight: FontWeight.w600,
          fontStyle: FontStyle.normal,
          letterSpacing: 0.0,
          height: 1.5,
        ),
        labelSmall: TextStyle(
          fontFamily: "Heebo",
          fontSize: 11.0,
          fontWeight: FontWeight.normal,
          fontStyle: FontStyle.normal,
          letterSpacing: 0.0,
          height: 1.45,
        ),
      );
}
