import 'package:flutter/material.dart';

class AppTheme {
  ThemeData get themeData => ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          primary: Color(0XFFa076f2),
          onBackground: Color(0XFF555555),
          background: Color(0XFFf7f7f7),
          surface: Color(0XFFFFFFFF),
          onSurface: Color(0XFF9e9e9e),
          onPrimary: Color(0XFFFFFFFF),
          secondary: Color(0XFFFFFFFF),
          onSecondary: Color(0XFFFFFFFF),
          surfaceTint: Color(0XFFf7f7f7),
          error: Color(0XFFFFFFFF),
          onError: Color(0XFFFFFFFF),
          shadow: Color(0XFFf7f7f7),
          brightness: Brightness.light,
        ),
        textTheme: const TextTheme(
          displayLarge: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.w600,
            fontStyle: FontStyle.normal,
            fontSize: 30,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          displayMedium: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.w700,
            fontStyle: FontStyle.normal,
            fontSize: 22,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          displaySmall: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 20,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          headlineMedium: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 18,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          headlineSmall: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 16,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          titleLarge: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 14,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          titleMedium: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.w600,
            fontStyle: FontStyle.normal,
            fontSize: 20,
            letterSpacing: 0.09,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          titleSmall: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.w600,
            fontStyle: FontStyle.normal,
            fontSize: 18,
            letterSpacing: 0.09,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          bodyLarge: TextStyle(
            fontFamily: 'Heebo',
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 18,
            letterSpacing: 0,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          bodyMedium: TextStyle(
            fontFamily: 'Heebo',
            fontSize: 16,
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            letterSpacing: 0,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          bodySmall: TextStyle(
            fontFamily: 'Heebo',
            fontSize: 14,
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            letterSpacing: 0,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          labelLarge: TextStyle(
            fontFamily: 'Heebo',
            fontSize: 16,
            fontWeight: FontWeight.w600,
            fontStyle: FontStyle.normal,
            letterSpacing: 0,
            height: 1.5,
            color: Color(0XFF555555),
          ),
          labelSmall: TextStyle(
            fontFamily: 'Heebo',
            fontSize: 11,
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            letterSpacing: 0,
            height: 1.45,
            color: Color(0XFF555555),
          ),
        ),
      );
}
