name: book_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-246.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql: ^5.1.3
  get_it: ^7.6.0
  result_dart: ^1.0.6
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0




flutter:

  uses-material-design: true
  uses-material-design: true
  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Heebo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Heebo-Light.ttf
          weight: 300
        - asset: assets/fonts/Heebo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Heebo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Heebo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Heebo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Heebo-ExtraBold.ttf
          weight: 800
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
